# Generated by Django 3.1.6 on 2021-02-26 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210225_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
